export const DEFAULT_ACCOUNTS = [
  // Assets
  { code: "1000", name: "Cash",                              type: "Asset",        normalBalance: "debit",  isContra: false },
  { code: "1010", name: "Petty Cash",                        type: "Asset",        normalBalance: "debit",  isContra: false },
  { code: "1100", name: "Accounts Receivable",               type: "Asset",        normalBalance: "debit",  isContra: false },
  { code: "1110", name: "Allowance for Doubtful Accounts",   type: "Asset",        normalBalance: "credit", isContra: true  },
  { code: "1200", name: "Inventory",                         type: "Asset",        normalBalance: "debit",  isContra: false },
  { code: "1300", name: "Prepaid Expenses",                  type: "Asset",        normalBalance: "debit",  isContra: false },
  { code: "1400", name: "Short-term Investments",            type: "Asset",        normalBalance: "debit",  isContra: false },
  { code: "1500", name: "Property, Plant & Equipment",       type: "Asset",        normalBalance: "debit",  isContra: false },
  { code: "1510", name: "Accumulated Depreciation",          type: "Asset",        normalBalance: "credit", isContra: true  },
  { code: "1600", name: "Intangible Assets",                 type: "Asset",        normalBalance: "debit",  isContra: false },
  { code: "1610", name: "Accumulated Amortisation",          type: "Asset",        normalBalance: "credit", isContra: true  },
  { code: "1700", name: "Loans Receivable",                  type: "Asset",        normalBalance: "debit",  isContra: false },
  // Liabilities
  { code: "2000", name: "Accounts Payable",                  type: "Liability",    normalBalance: "credit", isContra: false },
  { code: "2100", name: "Wages Payable",                     type: "Liability",    normalBalance: "credit", isContra: false },
  { code: "2200", name: "PAYE / Tax Payable",                type: "Liability",    normalBalance: "credit", isContra: false },
  { code: "2300", name: "Unearned Revenue",                  type: "Liability",    normalBalance: "credit", isContra: false },
  { code: "2400", name: "Short-term Loans Payable",          type: "Liability",    normalBalance: "credit", isContra: false },
  { code: "2500", name: "Credit Card Payable",               type: "Liability",    normalBalance: "credit", isContra: false },
  { code: "2600", name: "Long-term Loans Payable",           type: "Liability",    normalBalance: "credit", isContra: false },
  // Equity
  { code: "3000", name: "Owner's Capital / Share Capital",   type: "Equity",       normalBalance: "credit", isContra: false },
  { code: "3100", name: "Retained Earnings",                 type: "Equity",       normalBalance: "credit", isContra: false },
  { code: "3200", name: "Drawings / Dividends Paid",         type: "Equity",       normalBalance: "debit",  isContra: false },
  // Revenue
  { code: "4000", name: "Service Revenue",                   type: "Revenue",      normalBalance: "credit", isContra: false },
  { code: "4100", name: "Product / Sales Revenue",           type: "Revenue",      normalBalance: "credit", isContra: false },
  { code: "4200", name: "Interest Income",                   type: "Revenue",      normalBalance: "credit", isContra: false },
  { code: "4300", name: "Rental Income",                     type: "Revenue",      normalBalance: "credit", isContra: false },
  { code: "4400", name: "Gain on Asset Disposal",            type: "NonOperating", normalBalance: "credit", isContra: false },
  { code: "4500", name: "Purchase Discounts Received",       type: "Revenue",      normalBalance: "credit", isContra: false },
  // Cost of Sales
  { code: "5000", name: "Cost of Goods Sold",                type: "CostOfSales",  normalBalance: "debit",  isContra: false },
  { code: "5100", name: "Direct Labour",                     type: "CostOfSales",  normalBalance: "debit",  isContra: false },
  // Operating Expenses
  { code: "6000", name: "Salaries & Wages Expense",          type: "Expense",      normalBalance: "debit",  isContra: false },
  { code: "6100", name: "Rent Expense",                      type: "Expense",      normalBalance: "debit",  isContra: false },
  { code: "6200", name: "Utilities Expense",                 type: "Expense",      normalBalance: "debit",  isContra: false },
  { code: "6300", name: "Marketing & Advertising",           type: "Expense",      normalBalance: "debit",  isContra: false },
  { code: "6400", name: "Travel & Entertainment",            type: "Expense",      normalBalance: "debit",  isContra: false },
  { code: "6500", name: "Depreciation Expense",              type: "Expense",      normalBalance: "debit",  isContra: false },
  { code: "6600", name: "Bad Debts Expense",                 type: "Expense",      normalBalance: "debit",  isContra: false },
  { code: "6700", name: "Insurance Expense",                 type: "Expense",      normalBalance: "debit",  isContra: false },
  { code: "6800", name: "Professional Fees",                 type: "Expense",      normalBalance: "debit",  isContra: false },
  { code: "6900", name: "General & Administrative",          type: "Expense",      normalBalance: "debit",  isContra: false },
  // Non-Operating
  { code: "7000", name: "Interest Expense",                  type: "NonOperating", normalBalance: "debit",  isContra: false },
  { code: "7100", name: "Loss on Asset Disposal",            type: "NonOperating", normalBalance: "debit",  isContra: false },
  { code: "7200", name: "Foreign Exchange Loss",             type: "NonOperating", normalBalance: "debit",  isContra: false },
  { code: "7300", name: "Income Tax Expense",                type: "NonOperating", normalBalance: "debit",  isContra: false },
] as const;
